flask_tracking/tracking/models.py
from flask_tracking.data import CRUDMixin, db


import datetime

class Entry(CRUDMixin, db.Model):
    __tablename__ = 'tracking_entries'


    user_id = db.Column(db.Integer, db.ForeignKey('users_user.id'))
    punchIn = db.Column(db.TIMESTAMP)
    punchOut = db.Column(db.TIMESTAMP, default = datetime.datetime.min)
    punchInComment = db.Column(db.String)
    punchOutComment = db.Column(db.String)
    id = db.Column(db.Integer, primary_key = True)

    def __repr__(self):
        return '<Entry {:d}>'.format(self.id)

    def __init__(self, user_id=None):
        self.user_id = user_id
        self.punchIn = datetime.datetime.now()

    def punch_out(self):
        self.punchOut = datetime.datetime.now()
        db.session.commit()

    def updateComment(self, comment):
        self.punchOutComment = comment
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def __str__(self):
        return str(self.punchOut)

class Visit(CRUDMixin, db.Model):
    __tablename__ = 'tracking_visit'

    browser = db.Column(db.String)
    date = db.Column(db.DateTime)
    event = db.Column(db.String)
    url = db.Column(db.String)
    ip_address = db.Column(db.String)
    location = db.Column(db.String)
    latitude = db.Column(db.Numeric)
    longitude = db.Column(db.Numeric)
    site_id = db.Column(db.Integer, db.ForeignKey('tracking_site.id'))

    def __repr__(self):
        r = '<Visit for site ID {:d}: {} - {:%Y-%m-%d %H:%M:%S}>'
        return r.format(self.site_id, self.url, self.date)


class Site(CRUDMixin, db.Model):
    __tablename__ = 'tracking_site'

    base_url = db.Column(db.String)
    visits = db.relationship('Visit', backref='site', lazy='select')
    user_id = db.Column(db.Integer, db.ForeignKey('users_user.id'))

    def __repr__(self):
        return '<Site {:d} {}>'.format(self.id, self.base_url)

    def __str__(self):
        return self.base_url

flask_tracking/tracking/forms.py
from datetime import datetime as dt

from flask.ext.wtf import Form
from wtforms import fields
from wtforms.validators import Required
from wtforms.ext.sqlalchemy.fields import QuerySelectField

from .models import Site


class PunchInForm(Form):
	punch_in_comment = fields.TextField(validators=[Required()])

class VisitForm(Form):
    browser = fields.StringField()
    date = fields.DateField(default=dt.now)
    event = fields.StringField()
    url = fields.StringField(validators=[Required()])
    ip_address = fields.StringField()
    site = QuerySelectField(validators=[Required()], query_factory=lambda: Site.query.all())

flask_tracking/tracking/views.py
from flask import abort, Blueprint, flash, jsonify, Markup, redirect, render_template, request, url_for
from flask.ext.login import current_user, login_required

from .forms import PunchInForm, VisitForm

from .models import Site, Entry
from ..users.models import User

from flask_tracking.data import query_to_list
import datetime

tracking = Blueprint("tracking", __name__)


@tracking.route("/")
def index():
    if not current_user.is_anonymous():
        return redirect(url_for(".view_sites"))
    return render_template("index.html")


@tracking.route("/sites/<int:site_id>")
@login_required
def view_site_visits(site_id=None):
    site = Site.get_or_404(site_id)
    if not site.user_id == current_user.id:
        abort(401)

    query = Visit.query.filter(Visit.site_id == site_id)
    data = query_to_list(query)
    return render_template("tracking/site.html", visits=data, site=site)

def prettyEntries(e):
    l = []
    for t in e:
        g = []
        for cell in t:
            if type(cell) is str or type(cell) is unicode or  len(g) == 0:
                g.append(cell)
            elif cell is None:
                g.append("")
            else:
                if (cell.year == 1):
                    g.append("In Progress")
                else:
                    g.append(cell.strftime('%Y-%m-%d %H:%M'))
        l.append(g)
    return l


@tracking.route("/timecards/<int:user_id>")
def listTimecards(user_id = None):
    timecards = Entry.query.filter(Entry.user_id == user_id).with_entities(Entry.id, Entry.punchIn, Entry.punchOut,Entry.punchOutComment).all()
    l = prettyEntries(timecards)
    return render_template("tracking/entries.html", entries=l, user_id=user_id)

@tracking.route("/timecards/all")
def allTimecards():
    timecards = User.query.all()
    return render_template("tracking/all.html", users=timecards)


@tracking.route("/timecards/<int:user_id>/punchIn")
def punch_in(user_id=None):
    entry = Entry.create(user_id=user_id)
    timecards = Entry.query.filter(Entry.user_id == user_id).with_entities(Entry.id, Entry.punchIn, Entry.punchOut,Entry.punchOutComment).all()
    l = prettyEntries(timecards)

    return render_template("tracking/entries.html", entries=l, user_id=user_id)

@tracking.route("/timecards/<int:user_id>/<int:entry_id>/punchOut")
def punch_out(user_id, entry_id):    
    e = Entry.query.filter(Entry.id == entry_id).one()
    if e.punchOut == datetime.datetime.min:
        e.punch_out()
        return e.punchOut.strftime('%Y-%m-%d %H:%M'),200
    return '',400

    #return render_template("tracking/entries.html", entries=l, user_id=user_id)

@tracking.route("/timecards/<int:user_id>/<int:entry_id>/updateComment", methods=["POST", "GET"])
def updateComment(user_id, entry_id):    
    comment = request.values.get("comment")
    entry = Entry.query.filter(Entry.id == entry_id).one()
    entry.updateComment(comment);


    return '',200

@tracking.route("/timecards/<int:user_id>/<int:entry_id>/deleteEntry", methods=["GET"])
def deleteEntry(user_id, entry_id):    
    entry = Entry.query.filter(Entry.id == entry_id).one()
    entry.delete();

    return '',200




@tracking.route("/sites", methods=("GET", "POST"))
@login_required
def view_sites():
    form = PunchInForm()

    if form.validate_on_submit():
        Entry.create(owner=current_user, **form.data)
        flash("Punched In")
        return redirect(url_for(".punchOut"))

    query = Entry.query.filter(Entry.user_id == current_user.id)
    data = query_to_list(query)
    results = []

    try:
  
        results = [next(data)]
        for row in data:
            row = [_make_link(cell) if i == 0 else cell
                   for i, cell in enumerate(row)]
            results.append(row)
    except StopIteration:

        pass

    return render_template("tracking/entries.html", entries=results, form=form)


_LINK = Markup('<a href="{url}">{name}</a>')


def _make_link(site_id):
    url = url_for(".view_site_visits", site_id=site_id)
    return _LINK.format(url=url, name=site_id)

flask_tracking/templates/tracking/all.html
{% extends "layout.html" %}
{% import "helpers/tables.html" as tables %}
{% block title %}View entries{% endblock %}
{% block content %}
{{ super() }}

<style type="text/css">
	.timecard tr td{
		padding-right:30px;
	}
</style>

<script type="text/javascript">
function updateComment(e, elem){
	a = prompt("Enter a comment"); 
	$.ajax({
	type: "POST",
	url: "/timecards/{{user_id}}/" + e + "/updateComment",
	data: {"comment" : a },
	dataType: "json",
	success: function () {  elem.innerHTML = a; }
	});
}

function deleteComment(e, elem){
	$.ajax({
	type: "GET",
	url: "/timecards/{{user_id}}/" + e + "/deleteEntry",
	success: function () {  elem.parentNode.removeChild(elem) }
	});

}

function punchOut(e, elem){
	$.ajax({
	type: "GET",
	url: "/timecards/{{user_id}}/" + e + "/punchOut",
	success: function (r) {  elem.innerHTML = r; }
	});

}

</script>

{% for user in users %}
<h2>{{user.name}}</h2>
<table class="timecard">
	<tr>
		<td align='center'>Clock in time</td>
		<td align='center'>Clock out time</td>
		<td align='center'>Comments</td>
	</tr>
{% for t in user.entries %}
    <tr>
    	<td>{{t.punchIn}}</td>
    	<td>{{t.punchOut}}</td>
    	<td>{{t.punchOutComment}}</td>
    </tr>
{% endfor %}
{% endfor %}
</table>
{% endblock content %}

flask_tracking/templates/tracking/entries.html
{% extends "layout.html" %}
{% import "helpers/tables.html" as tables %}
{% block title %}View entries{% endblock %}
{% block content %}
{{ super() }}

<style type="text/css">
	#timecard tr td{
		padding-right:30px;
	}
</style>

<table id="timecard">
	<tr>
		<td align='center'>Clock in time</td>
		<td align='center'>Clock out time</td>
		<td align='center'>Comments</td>
	</tr>
{% for t in entries %}
    <tr>
    	{% for i in range(1,3) %}
        	<td>{{ t[i] }}</td>
        {% endfor %}
    </tr>
{% endfor %}

</table>
{% endblock content %}

flask_tracking/templates/tracking/punchIn.html
{% extends "layout.html" %}
{% import "helpers/tables.html" as tables %}
{% block title %}View visits for {{ site.base_url }}{% endblock %}
{% block content %}
{{ super() }}
<p>To track visits to this site, simple add the following snippet to the pages that you wish to track:</p>
<code><pre>
&lt;script>
(function() {
	var img = new Image();
	img.src = "{{ url_for('tracking.add_visit', site_id=site.id, event='PageLoad', _external=true) }}";
})();
&lt;/script>
&lt;noscript>
&lt;img src="{{ url_for('tracking.add_visit', site_id=site.id, event='PageLoad', _external=true) }}" width="1" height="1" />
&lt;/noscript>
</pre></code>
<h2>Visits for {{ site.base_url }}</h2>
<table>
{{ tables.render(visits) }}
</table>
{% endblock content %}

flask_tracking/templates/tracking/site.html
{% extends "layout.html" %}
{% import "helpers/tables.html" as tables %}
{% block title %}View visits for {{ site.base_url }}{% endblock %}
{% block content %}
{{ super() }}
<p>To track visits to this site, simple add the following snippet to the pages that you wish to track:</p>
<code><pre>
&lt;script>
(function() {
	var img = new Image();
	img.src = "{{ url_for('tracking.add_visit', site_id=site.id, event='PageLoad', _external=true) }}";
})();
&lt;/script>
&lt;noscript>
&lt;img src="{{ url_for('tracking.add_visit', site_id=site.id, event='PageLoad', _external=true) }}" width="1" height="1" />
&lt;/noscript>
</pre></code>
<h2>Visits for {{ site.base_url }}</h2>
<table>
{{ tables.render(visits) }}
</table>
{% endblock content %}

flask_tracking/templates/tracking/sites.html
{% extends "layout.html" %}
{% import "helpers/forms.html" as forms %}
{% import "helpers/tables.html" as tables %}
{% block title %}Available Sites{% endblock %}
{% block content %}
{{super()}}
<form action="{{url_for('tracking.view_sites')}}" method="POST">
<fieldset>
<legend>Punch In</legend>
{{ forms.render(form) }}
<p><input type="Submit" value="Punch In"></p>
</fieldset>
</form>
<table>
{{ tables.render(sites) }}
</table>
{% endblock content %}